coverage:
  range: 40..60
  round: nearest
  precision: 2


ignore:
  - "dfxml_schema/**"
  - "src/be20_api/catch.hpp"
  - "src/be20_api/cxxopts.hpp"
  - "src/be20_api/dfxml_cpp/**"
  - "src/be20_api/dfxml_schema/**"
  - "src/be20_api/thread-pool/**"
  - "src/be20_api/utfcpp/**"
  - "src/rar/**"
