// This file is generated by autoconf.  Do not edit this file.
public final class Config {
  private Config() { } // no constructor
  /** BEViewer Version {@value} */
  public static final String VERSION = "1.3.1";
}
