#!/bin/sh

# For DFRWS2013 challenge

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR="$( dirname "${BASH_SOURCE[0]}")"
args="--quiet"
export PATH=$DIR:$PATH

PYTHON=python3.3
if [ x`which $PYTHON` == x ]; then
  PYTHON=python3.2
fi
if [ x`which $PYTHON` == x ]; then
  PYTHON=python3
fi
if [ x`which $PYTHON` == x ]; then
  echo This program requires python3.3, python3.2 or python3
  exit 1
fi


#
# Implemenet the DFRWS 2013 challenge
if [ $1 == "-d" ]; then
  args=""
  shift 1
fi

if [ $# == 2 ]; then
  $PYTHON $DIR/dfrws_2012_challenge.py $args "$1" "$2" 
  exit 0
fi
if [ $# == 3 ]; then
  $PYTHON $DIR/dfrws_2012_challenge.py $args "$1" "$2" "$3"
  exit 0
fi
  
echo usage $0 'target blocksize [concurrency factor]'
echo example: $0 target.dd 512
exit 1
