name: Create source distribution

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DEBUG_5G: FALSE
      DEBUG_FAST: FALSE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract version
        id: extract_version
        run: |
          version=$(grep 'AC_INIT(\[BULK_EXTRACTOR\]' configure.ac | cut -d',' -f2 | tr -d '[]')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Install Ubuntu dependencies
        run: echo "" | bash etc/CONFIGURE_UBUNTU22LTS.bash

      - name: Bootstrap
        run: bash bootstrap.sh

      - name: Configure
        run: ./configure --quiet

      - name: Build and validate source distribution
        run: make distcheck

      - name: Upload source distribution
        uses: actions/upload-artifact@v4
        with:
          name: bulk_extractor-${{ steps.extract_version.outputs.version }}
          path: bulk_extractor-${{ steps.extract_version.outputs.version }}.tar.gz
          if-no-files-found: error
